### ISSUE TITLE
generalize to multiple volumes

### ISSUE THREAD

**Issue by adamlauretig** [adamlauretig/independent_study#5]
is currently throwing a bug:

Traceback (most recent call last):
  File "/Users/adamlauretig/data/independent_study/get_all_docs.py", line 56, in <module>
    if len(str(doc2.date['when'])) > 10:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bs4/element.py", line 997, in __getitem__
    return self.attrs[key]
KeyError: 'when'

**Comment by adamlauretig** [comment]
fixed this, grep for "when" as logical
